version: '3.1'

services:
  gitautomation:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
      
  gitautomationsql:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
