version: '3.1'

services:
  gitautomation:
    image: gitautomation
    build:
      context: ./GitAutomation
      dockerfile: Dockerfile
    secrets:
      - gitcredentials
    networks:
      - backend
  gitautomationsql:
    image: gitautomation-sql
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile
    networks:
      - backend


secrets:
  gitcredentials:
    file: ./git-credentials.txt

networks:
  backend:
