version: '3.1'

services:
  gitautomation:
    image: gitautomation
    build:
      context: ./GitAutomation
      dockerfile: Dockerfile
    secrets:
      - gitcredentials
  gitautomationsql:
    image: gitautomation-sql
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile


secrets:
  gitcredentials:
    file: ./git-credentials.txt

